INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Купіца', 'вулиця Братів Рогатинців, 18', 'обіднє меню з 12.00 до 16.00', 'Цілодобово (у вихідні дні )', '1', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Білий Лев', '15, вулиця Лесі Українки, Львів', 'обіднє меню з 12.00 до 16.00', '12.00 - 02.00', '0', '1', '1', '0', '1', '0', '1', '1', '1');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Трапезна УКУ', 'вулиця Козельницька, 2А', 'Великий та недорогий асортимент', '08.30 - 19.00', '1', '1', '0', '1', '0', '1', '0', '1', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Bar Mushly', 'Kam\'yanytsya Maydashevychivsʹka, площа Ринок, ', 'Сніданок за 70 грн', '07.30 - 00.00', '1', '1', '1', '0', '0', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Корки і крихти', 'вулиця Лесі Українки, 27', '125 грн сніданок', '09.00 - 23.00', '1', '1', '1', '0', '0', '1', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('L\'affinage cheese&wine', 'проїзд Крива Липа, 7', 'Сніданок від 85 грн до 125 грн', '11.00 - 23.00', '1', '1', '0', '1', '0', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Shoko', 'вулиця Академіка Андрія Сахарова, 44', 'Сніданок від 90 грн до 150 грн', '09.00 - 23.00', '0', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Cups and plates', 'вулиця Братів Рогатинців, 43/12', 'обіднє меню', '09.00 - 22.00', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('LV caffe', 'вулиця Січових Стрільців,7', 'Bussines lunch', '12.00 - 00.00', '0', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Port wine bar', 'вулиця Валова, 19', 'Щовівторка 2+1 ', '11.00 - 23.00', '0', '1', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Кумпель', 'вулиця Чорновола, 2Б;  вулиця Володимира Винничиенка 6', 'Великий та недорогий асортимент', '11.00 - 00.00', '0', '1', '1', '0', '0', '0', '1', '1', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Час поїсти', 'вулиця Миколи Коперника 3', 'Великий та недорогий асортимент', '09.00 - 22.00', '0', '1', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Хмільний дім Роберта Домса', 'вулиця Клепарівська, 18', 'Business lunch у будні 13.00 - 16.00', '12.00 - 00.00', '1', '1', '1', '0', '1', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Сіли з\'їли', 'вулиця Київська 7', 'Дешева піца', '10.00 - 22.00', '1', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Сало', 'проспект Свободи, 6/8,', 'Business lunch у будні 12.00 - 15.00', '12.00 - 00.00', '1', '1', '1', '0', '0', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Pizza House', 'вулиця Степана Бандери, 25', 'Комлексні обіди (які приносять надзвичайно швидко)', '09.00 - 21.00', '0', '1', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Містечко', 'вулиця Модеста Менцинського, 12', 'Великий та недорогий асортимент', '09.00 - 22.30', '1', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Скотина', 'вулиця Наукова 7Б', 'Щодня з 17.00 - 19.00 (1+1) на окреме меню', '11.00 - 22.00', '1', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Цісар', 'вулиця Городоцька 65', 'Великий та недорогий асортимент', 'Цілодобово', '0', '1', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Смачні Сезони', 'вулиця Залізнична 2', 'Великий та недорогий асортимент', '08.00 - 22.00', '1', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Фабрика їжі \"Біля Магнуса\"', 'вулиця Шпитальна, 1', 'Великий та недорогий асортимент', 'Цілодобово', '0', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Мандрівник', 'вулиця Лесі Українки, 39', 'Великий та недорогий асортимент', '10.00 - 20.00', '1', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Пузата Хата', 'проспект Шевченка, 10', 'Великий та недорогий асортимент', '08.00 - 23.00', '0', '1', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO `cafes` (`title`, `address`, `actions`, `workingHours`, `wiFi`, `paymentByCard`, `discount`, `vegetarianMenu`, `liveMusic`, `businessLunch`, `alcohol`, `terrace`, `allNight`) VALUES ('Crazy Town', 'проспект Шевченка, 7', 'Щасливі години (будні 19.00 - 20.00)', '11.00 - 02.00', '1', '1', '1', '0', '0', '0', '1', '0', '0');

UPDATE `cafes` SET `nearYou`='1' WHERE `id`='12';
UPDATE `cafes` SET `nearYou`='1' WHERE `id`='16';
UPDATE `cafes` SET `nearYou`='1' WHERE `id`='20';
UPDATE `cafes` SET `nearYou`='1' WHERE `id`='24';

UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'25.7\"N 24°02\'00.2\"E\n' WHERE `id`='1';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'38.4\"N 24°01\'49.4\"E' WHERE `id`='2';
UPDATE `bomj-trip`.`cafes` SET `location`='49°49\'02.3\"N 24°01\'24.0\"E\n' WHERE `id`='3';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'33.6\"N 24°01\'50.7\"E\n' WHERE `id`='4';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'38.7\"N 24°01\'53.7\"E\n' WHERE `id`='5';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'26.3\"N 24°01\'33.7\"E\n' WHERE `id`='6';
UPDATE `bomj-trip`.`cafes` SET `title`='SHOco', `location`='49°49\'43.4\"N 24°00\'43.9\"E\n' WHERE `id`='7';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'27.3\"N 24°02\'02.0\"E\n' WHERE `id`='8';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'28.3\"N 24°01\'32.1\"E\n' WHERE `id`='9';
UPDATE `bomj-trip`.`cafes` SET `location`='50°00\'11.3\"N 36°14\'49.9\"E\n' WHERE `id`='10';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'49.1\"N 24°01\'33.3\"E\n' WHERE `id`='11';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'20.8\"N 24°01\'40.9\"E\n' WHERE `id`='12';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'52.0\"N 24°00\'56.5\"E\n' WHERE `id`='13';
UPDATE `bomj-trip`.`cafes` SET `location`='49°49\'58.9\"N 24°00\'38.9\"E\n' WHERE `id`='14';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'24.5\"N 24°01\'45.8\"E\n' WHERE `id`='15';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'04.8\"N 24°00\'52.6\"E\n' WHERE `id`='16';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'35.6\"N 24°01\'19.9\"E\n' WHERE `id`='17';
UPDATE `bomj-trip`.`cafes` SET `location`='49°48\'10.3\"N 24°00\'08.0\"E\n' WHERE `id`='18';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'30.9\"N 24°01\'00.2\"E\n' WHERE `id`='19';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'20.0\"N 24°00\'10.7\"E\n' WHERE `id`='20';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'41.3\"N 24°01\'27.7\"E\n' WHERE `id`='21';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'37.7\"N 24°01\'58.2\"E\n' WHERE `id`='22';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'15.0\"N 24°01\'52.4\"E\n' WHERE `id`='23';
UPDATE `bomj-trip`.`cafes` SET `location`='49°50\'21.8\"N 24°01\'53.7\"E\n' WHERE `id`='24';

UPDATE `bomj-trip`.`cafes` SET `title` = 'Kupitsa', `address` = 'Brativ Rohatyntsiv St, 18', `actions` = 'business lunch from 12.00 to 16.00, Every Tuesday all tincture \"2 + 1\", weekdays - from 14.00 to 18.00 \"2 + 2\"', `workingHours` = '24 hours', `liveMusic` = '1', `businessLunch` = '1' WHERE (`id` = '1');
